version: "3"
services:
  influxdb:
    image: influxdb:latest
    container_name: mirror-influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
    env_file: .env
       # sourced from .env
       # sourced from .env
